### ISSUE TITLE
这个源还能用吗？

### ISSUE THREAD

**Issue by NBaby** [ElfSundae/CocoaPods-China-Mirror#1]
好像这个域名已经访问不了，这个源还更新不？有类似推荐吗

**Comment by ElfSundae** [comment]
现在用不了，没服务器.. 你是找 git 镜像还是 CDN 镜像？git 镜像可以试试清华源， CDN 目前好像还没有国内镜像。

**Comment by NBaby** [comment]
就是找CDN的，都过去大半年了。。虽然伸手党很不好。。看来只能先down master了，国内网络伤不起。

**Comment by ElfSundae** [comment]
嗯，伤不起
